### ISSUE TITLE
Implement Firebase

### ISSUE THREAD

**Issue by loljoho** [happyhournyc/webapp#1]
# Implement Firebase (Epic)

## Task List

 - [ ] Configure Firebase Application
 - [ ] Implement Authentication
 - [ ] Implement Realtime Database
 - [ ] Enable Offline Capabilities

## External Links
 - [happyhournyc Firebase Console][firebase-console]
 - [Documentation][firebase-overview]
 - [Get Started][firebase-get-started]
 - [API Reference][firebase-api-ref]
 - [Samples][firebase-samples]

[firebase-console]:https://console.firebase.google.com/project/happyhournyc-42ce8/overview
[firebase-overview]:https://firebase.google.com/docs
[firebase-get-started]:https://firebase.google.com/docs/web/setup
[firebase-api-ref]:https://firebase.google.com/docs/reference/js/
[firebase-samples]:https://firebase.google.com/docs/samples/#web

[firebase-docs-auth]:https://firebase.google.com/docs/auth/
[firebase-docs-auth-users]:https://firebase.google.com/docs/auth/users
[firebase-docs-auth-manage]:https://firebase.google.com/docs/auth/web/manage-users
[firebase-docs-auth-password]:https://firebase.google.com/docs/auth/web/password-auth
[firebase-docs-auth-google]:https://firebase.google.com/docs/auth/web/google-signin
[firebase-docs-auth-facebook]:https://firebase.google.com/docs/auth/web/facebook-login
[firebase-docs-auth-twitter]:https://firebase.google.com/docs/auth/web/twitter-login
[firebase-docs-auth-github]:https://firebase.google.com/docs/auth/web/github-auth
[firebase-docs-auth-custom]:https://firebase.google.com/docs/auth/web/custom-auth
[firebase-docs-auth-anonymous]:https://firebase.google.com/docs/auth/web/anonymous-auth
[firebase-docs-auth-account]:https://firebase.google.com/docs/auth/web/account-linking
[firebase-docs-auth-email]:https://firebase.google.com/docs/auth/custom-email-handler

[firebase-docs-db]:https://firebase.google.com/docs/database/
[firebase-docs-db-structure]:https://firebase.google.com/docs/database/web/structure-data
[firebase-docs-db-offline]:https://firebase.google.com/docs/database/web/offline-capabilities
[firebase-docs-db-security]:https://firebase.google.com/docs/database/security/

[firebase-refs-rest]:https://firebase.google.com/docs/reference/rest/database/
[firebase-refs-rest-auth]:https://firebase.google.com/docs/reference/rest/database/user-auth
[firebase-refs-db]:https://firebase.google.com/docs/reference/security/database/
[firebase-refs-db-regex]:https://firebase.google.com/docs/reference/security/database/regex

[firebase-samples]:https://firebase.google.com/docs/samples/
[firebase-libraries]:https://firebase.google.com/docs/libraries/
